# Generated by Django 5.2 on 2025-06-04 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_remove_article_content_articleparagraph_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_expiry_hours', models.PositiveIntegerField(default=24, help_text='Hours until share links expire')),
                ('max_shares_per_article', models.PositiveIntegerField(default=100, help_text='Maximum active shares per article')),
                ('require_authentication', models.BooleanField(default=False, help_text='Require login to view shared articles')),
                ('track_views', models.BooleanField(default=True, help_text='Track views on shared links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Share Settings',
                'verbose_name_plural': 'Share Settings',
            },
        ),
        migrations.CreateModel(
            name='SecureShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='kb.article')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLinkView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='kb.securesharelink')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securesharelink',
            index=models.Index(fields=['token'], name='kb_securesh_token_771604_idx'),
        ),
        migrations.AddIndex(
            model_name='securesharelink',
            index=models.Index(fields=['expires_at'], name='kb_securesh_expires_b184ad_idx'),
        ),
        migrations.AddIndex(
            model_name='securesharelink',
            index=models.Index(fields=['article', '-created_at'], name='kb_securesh_article_ce799d_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelinkview',
            index=models.Index(fields=['share_link', '-viewed_at'], name='kb_sharelin_share_l_54babe_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelinkview',
            index=models.Index(fields=['ip_address'], name='kb_sharelin_ip_addr_7891c6_idx'),
        ),
    ]
