# Generated by Django 5.2 on 2025-06-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_sharesettings_securesharelink_sharelinkview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securesharelink',
            name='paragraph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='kb.articleparagraph'),
        ),
    ]
