# Generated by Django 5.2 on 2025-06-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0009_articlecomment_articlerating_paragraphlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Space',
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name_plural': 'Spaces'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='space',
        ),
    ]
