# Generated by Django 5.2 on 2025-06-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0010_rename_category_to_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#007bff', 'Blue'), ('#28a745', 'Green'), ('#dc3545', 'Red'), ('#ffc107', 'Yellow'), ('#6f42c1', 'Purple'), ('#fd7e14', 'Orange'), ('#20c997', 'Teal'), ('#e83e8c', 'Pink'), ('#6c757d', 'Gray'), ('#17a2b8', 'Cyan')], default='#007bff', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.AddField(
            model_name='space',
            name='icon',
            field=models.CharField(choices=[('fas fa-folder', 'Folder'), ('fas fa-book', 'Book'), ('fas fa-lightbulb', 'Lightbulb'), ('fas fa-cog', 'Settings'), ('fas fa-rocket', 'Rocket'), ('fas fa-star', 'Star'), ('fas fa-heart', 'Heart'), ('fas fa-trophy', 'Trophy'), ('fas fa-graduation-cap', 'Education'), ('fas fa-code', 'Code'), ('fas fa-database', 'Database'), ('fas fa-shield-alt', 'Security'), ('fas fa-users', 'Team'), ('fas fa-chart-line', 'Analytics'), ('fas fa-puzzle-piece', 'Puzzle'), ('fas fa-tools', 'Tools'), ('fas fa-globe', 'Global'), ('fas fa-mobile-alt', 'Mobile'), ('fas fa-cloud', 'Cloud'), ('fas fa-fire', 'Fire')], default='fas fa-folder', max_length=50),
        ),
        migrations.AddField(
            model_name='space',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='kb.label'),
        ),
    ]
