# Generated by Django 5.2 on 2025-06-05 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0014_article_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_later', to='kb.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_later_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='kb_readlate_user_id_05ba15_idx'), models.Index(fields=['article', 'user'], name='kb_readlate_article_d0da51_idx')],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
