# Generated by Django 5.2 on 2025-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0015_readlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('archive', 'Archive')], default='draft', max_length=10),
        ),
    ]
